<?php

namespace AppBundle\Repository;

/**
 * RequestStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
